# -*- coding: utf-8 -*-
"""WebServer.ipynb
Automatically generated by Colab.
Original file is located at
https://colab.research.google.com/drive/1D70-a5bHAm4E9v5KpsH4gPbeHyZrDSz0
"""
#import socket module
from socket import *
import sys # In order to terminate the program
serverSocket = socket(AF_INET, SOCK_STREAM)
#Prepare a sever socket

server_port = 6292
serverSocket.bind(('', server_port))
serverSocket.listen(1)

#Fill in start
#Fill in end

print(f'Listening on port {server_port}')

while True:
    #Establish the connection
    print('Ready to serve...')

    connectionSocket, addr = serverSocket.accept() #Fill in start #Fill in end
    try:
        message = connectionSocket.recv(1024) #Fill in start #Fill in end
        filename = message.split()[1]
        f = open(filename[1:])
        outputdata = f.read() #Fill in start #Fill in end

        #Send one HTTP header line into socket
        #Fill in start
        http_and_headers = f'HTTP/1.1 200 OK\nContent-Type: text/html; encoding=utf8\nContent-Length:{len(outputdata)}\nConnection: close'
        connectionSocket.send(http_and_headers.encode())
        connectionSocket.send('\n\n'.encode())
        #Fill in end

        #Send the content of the requested file to the client
        for i in range(0, len(outputdata)):
            connectionSocket.send(outputdata[i].encode())
        connectionSocket.send("\r\n".encode())
        connectionSocket.close()
    except IOError:
        #Send response message for file not found
        #Fill in start
        response = 'HTTP/1.1 404 NOT FOUND\nContent-Type: text/html; encoding=utf8\nConnection: close'
        connectionSocket.send(response.encode())
        connectionSocket.send('\n\n'.encode())
        connectionSocket.send('404 File Not Found'.encode())
        #Fill in end

        #Close client socket
        #Fill in start
        connectionSocket.close()
        #Fill in end
serverSocke.close()
sys.exit()#Terminate the program after sending the corresponding data

